import { GoodsItem } from '../../interfaces/goodsItem'
export const goods: GoodsItem[] = [{
    id: 1,
    title: 'GIGABYTE GeForce RTX 3090 TI GAMING',
    description: 'Видеокарты GIGABYTE GeForce RTX 3090 TI GAMING обеспечивают рекордную производительность для геймеров, работая на базе Ampere — архитектуры NVIDIA RTX второго поколения. Они оснащены улучшенными ядрами RT и тензорными ядрами, потоковыми мультипроцессорами и высокоскоростной памятью G6X для потрясающих игровых возможностей.',
    price: 108999,
    rating: 4,
    stock: 17,
    brand: 'GIGABYTE',
    category: 'RTX 3090',
    images: ['../images/goodsImg/RTX3090/gigabyte3090.webp', '../images/goodsImg/RTX3090/gigabyte3090-2.webp'],
},
{
    id: 2,
    title: 'MSI GeForce RTX 3090 TI SUPRIM X',
    description: 'GeForce RTX 3090 Ti — невероятно мощные видеокарты с производительностью класса TITAN. В их основе лежит Ampere — архитектура NVIDIA RTX второго поколения — с удвоенной производительностью трассировки лучей и технологий искусственного интеллекта благодаря улучшенным ядрам RT, тензорным ядрам и потоковым мультипроцессорам. Видеокарты также оснащены впечатляющим объемом видеопамяти 24 ГБ G6X, призванным обеспечить исключительный уровень игры и творчества.',
    price: 112999,
    rating: 5,
    stock: 12,
    brand: 'MSI',
    category: 'RTX 3090',
    images: ['../images/goodsImg/RTX3090/MSI3090.webp', '../images/goodsImg/RTX3090/MSI3090-2.webp'],
}, {
    id: 3,
    title: 'Palit GeForce RTX 3090 TI GameRock',
    description: 'Серия Palit GameRock с дизайном «Ослепительный ангел», специально разработана для требовательных игроков-энтузиастов, которые хотят получить максимальный игровой опыт и оригинальную систему освещения ARGB. Серия GameRock предоставляет лучшие игровые функции, высочайшую эффективность охлаждения и превосходное качество видеокарты, что позволяет вам чувствовать себя настоящим рокером на игровой сцене. Как говорится, Palit - твой дом спалит.',
    price: 106999,
    rating: 4,
    stock: 24,
    brand: 'Palit',
    category: 'RTX 3090',
    images: ['../images/goodsImg/RTX3090/palit3090.webp', '../images/goodsImg/RTX3090/palit3090-2.webp'],
}, {
    id: 4,
    title: 'Palit GeForce RTX 3080 Ti GamingPro',
    description: 'Видеокарта Palit GeForce RTX 3080 Ti GamingPro [NED308T019KB-132AA] работает абсолютно бесшумно даже при нагрузках среднего уровня за счет технологии «0 децибел». При этом главное достоинство устройства состоит в том, что оно обеспечивает графику и частоту смены кадров на самом высоком уровне. Это позволяет использовать его для ускорения искусственного интеллекта, задействованного в играх и творческих приложениях. Для этого видеокарта Palit GeForce RTX 3080 Ti GamingPro [NED308T019KB-132AA] была оснащена графическим процессором GeForce RTX 3080 Ti с микроархитектурой NVIDIA Ampere, а также сразу 12 ГБ видеопамяти типа GDDR6X.',
    price: 94999,
    rating: 5,
    stock: 7,
    brand: 'Palit',
    category: 'RTX 3080',
    images: ['../images/goodsImg/RTX3080/palit3080.webp', '../images/goodsImg/RTX3080/palit3080-2.webp'],
}, {
    id: 5,
    title: 'GIGABYTE GeForce RTX 3080 Ti EAGLE OC',
    description: 'Видеокарта GIGABYTE GeForce RTX 3080 Ti EAGLE OC [GV-N308TEAGLE OC-12GD] работает в команде с многозадачным потоковым процессором NVIDIA GeForce. За счет этого она обеспечивает компьютеру рекордную производительность, удивляя даже бывалых геймеров. Устройство транслирует картинку с разрешением вплоть до Ultra HD 8K (7680x4320 точек на дюйм). Для увеличения срока службы видеокарта GIGABYTE GeForce RTX 3080 Ti EAGLE OC [GV-N308TEAGLE OC-12GD] была оснащена мощным охлаждением WINDFORCE 3X, которое представлено радиатором с 7 композитными трубками и 3 осевыми вентиляторами.',
    price: 98999,
    rating: 3,
    stock: 26,
    brand: 'GIGABYTE',
    category: 'RTX 3080',
    images: ['../images/goodsImg/RTX3080/Gigabyte3080.webp', '../images/goodsImg/RTX3080/Gigabyte3080-2.webp'],
}, {
    id: 6,
    title: 'MSI GeForce RTX 3080 Ti VENTUS 3X OC',
    description: 'Видеокарта MSI GeForce RTX 3080 Ti VENTUS 3X OC [RTX 3080 Ti VENTUS 3X 12G OC] способна удивить своей функциональностью даже завзятого геймера. Она может похвастать графическим процессором GeForce RTX 3080 Ti с микроархитектурой NVIDIA Ampere, 12 ГБ видеопамяти типа GDDR6X и возможностью транслировать изображение с разрешением до Ultra HD 8K (7680x4320). Это все, что нужно для самой увлекательной и насыщенной событиями игры!',
    price: 89999,
    rating: 5,
    stock: 3,
    brand: 'MSI',
    category: 'RTX 3080',
    images: ['../images/goodsImg/RTX3080/Msi3080.webp', '../images/goodsImg/RTX3080/Msi3080-2.webp'],
}, {
    id: 7,
    title: 'ASUS TUF Gaming GeForce RTX 3070 Ti OC Edition',
    description: 'Видеокарта ASUS TUF Gaming GeForce RTX 3070 Ti OC Edition относится к моделям лимитированной серии и предлагает требовательным поклонникам компьютерных игр высокий уровень мощности графики. В основе адаптера содержится процессор GeForce RTX семейства 3070 Ti, который отличается номинальной частотой в пределах 1575 МГц и частотой в режиме разгона до значения 1815 МГц. Возможности подключения представлены 3 разъемами DisplayPort и 2 HDMI.',
    price: 77499,
    rating: 4,
    stock: 15,
    brand: 'ASUS',
    category: 'RTX 3070',
    images: ['../images/goodsImg/RTX3070/Asus3070.webp', '../images/goodsImg/RTX3070/Asus3070-2.webp'],
}, {
    id: 8,
    title: 'GIGABYTE GeForce RTX 3070 Ti VISION OC',
    description: 'Видеокарта GIGABYTE GeForce RTX 3070 Ti VISION OC [GV-N307TVISION OC-8GD] располагает 8 ГБ памяти и оснащена шиной разрядностью 256 бит, поэтому быстро обрабатывает «сложную» графику и достойно себя покажет даже в самых требовательных играх, трансляции видеопотоков и других задачах. Модель поддерживает разрешение Ultra HD 8K, а технология трассировки лучшей способствует максимальной реалистичности и детализации изображения.',
    price: 63999,
    rating: 3,
    stock: 21,
    brand: 'GIGABYTE',
    category: 'RTX 3070',
    images: ['../images/goodsImg/RTX3070/Gigabyte3070.webp', '../images/goodsImg/RTX3070/Gigabyte3070-2.webp'],
}, {
    id: 9,
    title: 'MSI GeForce RTX 3070 Ti SUPRIM X',
    description: 'Видеокарта MSI GeForce RTX 3070 Ti SUPRIM X [RTX 3070 Ti SUPRIM X 8G] с архитектурой NVIDIA Ampere создана для революционного гейминга. Она обеспечивает непревзойденную производительность за счет RT и тензорных ядер, а также потоковых мультипроцессоров. При этом даже при самых активных нагрузках вам не стоит бояться перегрева, ведь видеокарта MSI GeForce RTX 3070 Ti SUPRIM X [RTX 3070 Ti SUPRIM X 8G] оснащена системой Tri Frozr 2S, которая отслеживает температуру. Также она дополнена синхронизируемой подсветкой MSI Mystic Light. Поставляется устройство вместе с кронштейном-держателем.',
    price: 77999,
    rating: 5,
    stock: 9,
    brand: 'MSI',
    category: 'RTX 3070',
    images: ['../images/goodsImg/RTX3070/MSI3070.webp', '../images/goodsImg/RTX3070/MSI3070-2.webp'],
}, {
    id: 10,
    title: 'Palit GeForce RTX 3060 DUAL OC',
    description: 'Видеокарта Palit GeForce RTX 3060 DUAL OC (LHR) [NE63060T19K9-190AD] представляет собой высокопроизводительное решение для профессиональных рабочих станций и игровых систем. Благодаря технологиям Ampere, мощному видеопроцессору и 12 ГБ памяти данная модель позволяет с легкостью решать любые задачи. Кроме того, графический ускоритель поддерживает трассировку лучей, за счет чего обеспечивается реалистичное изображение в играх. Для отвода тепла предусмотрено 2 осевых вентилятора с особой формой лопастей, благодаря чему рабочая температура не превышает 93°C.',
    price: 33999,
    rating: 4,
    stock: 15,
    brand: 'Palit',
    category: 'RTX 3060',
    images: ['../images/goodsImg/RTX3060/Palit3060.webp', '../images/goodsImg/RTX3060/Palit3060-2.webp'],
}, {
    id: 11,
    title: 'MSI GeForce RTX 3060 GAMING X',
    description: 'Видеокарта MSI GeForce RTX 3060 GAMING X (LHR) [RTX 3060 GAMING X 12G] обладает высокой производительностью, благодаря чему может станет отличным выбором для настольных игровых и рабочих систем. Основой данной модели является многоядерный блок с поддержкой трассировки лучей, который дополнен 12 ГБ скоростной видеопамяти. Благодаря такому сочетанию графический ускоритель способен обеспечить высокую производительность для комфортного решения любых творческих и рабочих задач. Другой особенностью модели является эффективная и сравнительно тихая система охлаждения, благодаря которой обеспечивается минимально возможная температура компонентов под нагрузкой.',
    price: 36299,
    rating: 5,
    stock: 11,
    brand: 'MSI',
    category: 'RTX 3060',
    images: ['../images/goodsImg/RTX3060/MSI3060.webp', '../images/goodsImg/RTX3060/MSI3060-2.webp'],
}, {
    id: 12,
    title: 'ASUS GeForce RTX 3060 STRIX GAMING OC',
    description: 'Видеокарта ASUS GeForce RTX 3060 STRIX GAMING OC (LHR) разработана для самых требовательных геймеров. Она сочетает в себе исключительно высокий уровень мощности, эффективное отведение тепла, стабильность и эффектный внешний вид. Процессор GeForce RTX семейства 3060 отличается номинальной частотой в пределах 1320 МГц, В оснащение данной модели входят также 12 ГБ видеопамяти.',
    price: 51999,
    rating: 5,
    stock: 6,
    brand: 'ASUS',
    category: 'RTX 3060',
    images: ['../images/goodsImg/RTX3060/Asus3060.webp', '../images/goodsImg/RTX3060/Asus3060-2.webp'],
}, {
    id: 13,
    title: 'MSI GeForce RTX 3050 AERO ITX OC',
    description: 'Видеокарта GeForce RTX 3050 создана на базе высокопроизводительной архитектуры NVIDIA Ampere. Отличная производительность для игр и работы с графикой благодаря улучшенным ядрам RT и тензорным ядрам, потоковым мультипроцессорам и высокоскоростной памяти G6. Вооружитесь мощностью видеокарт GeForce RTX.',
    price: 23999,
    rating: 3,
    stock: 14,
    brand: 'MSI',
    category: 'RTX 3050',
    images: ['../images/goodsImg/RTX3050/MSI3050.webp', '../images/goodsImg/RTX3050/MSI3050-2.webp'],
}, {
    id: 14,
    title: 'ASUS ROG Strix GeForce RTX 3050 OC Edition',
    description: 'Видеокарта GeForce RTX 3050 создана на базе высокопроизводительной архитектуры NVIDIA Ampere. Отличная производительность для игр и работы с графикой благодаря улучшенным ядрам RT и тензорным ядрам, потоковым мультипроцессорам и высокоскоростной памяти G6. Вооружитесь мощностью видеокарт GeForce RTX.',
    price: 53999,
    rating: 5,
    stock: 20,
    brand: 'ASUS',
    category: 'RTX 3050',
    images: ['../images/goodsImg/RTX3050/ASUS3050.webp', '../images/goodsImg/RTX3050/ASUS3050-2.webp'],
}, {
    id: 15,
    title: 'GIGABYTE AORUS GeForce RTX 3050 ELITE',
    description: 'GIGABYTE AORUS GeForce RTX 3050 ELITE обеспечивают оптимальную производительность в топовых играх благодаря возможностям Ampere — архитектуры NVIDIA RTX второго поколения. Оптимальная производительность и качество графики благодаря улучшенным ядрам RT и тензорным ядрам, потоковым мультипроцессорам и высокоскоростной памяти G6.',
    price: 32999,
    rating: 4,
    stock: 18,
    brand: 'GIGABYTE',
    category: 'RTX 3050',
    images: ['../images/goodsImg/RTX3050/Gigabyte3050.webp', '../images/goodsImg/RTX3050/Gigabyte3050-2.webp'],
}, {
    id: 16,
    title: 'Palit GeForce RTX 4090 GameRock OmniBlack',
    description: 'Версия GeForce RTX 40 GameRock OmniBlack создана для любителей чистого черного цвета. Не отвлекаясь на подсветку, геймеры и создатели контента могут погрузиться в абсолютно темную среду всей душой. Простой, но изысканный дизайн с черными кристаллами демонстрирует высококлассный игровой стиль пользователя. Присмотревшись, вы заметите, что мерцающие звезды достали с неба и встроили в поверхность кожуха системы охлаждения, что делает GameRock OmniBlack настоящим произведением искусства и мощной игровой видеокартой даже без RGB-подсветки.',
    price: 137999,
    rating: 5,
    stock: 2,
    brand: 'Palit',
    category: 'RTX 4090',
    images: ['../images/goodsImg/RTX4090/Palit4090.webp', '../images/goodsImg/RTX4090/Palit4090-2.webp'],
}, {
    id: 17,
    title: 'GIGABYTE GeForce RTX 4090 GAMING OC',
    description: 'Графические процессоры NVIDIA GeForce RTX 40 обеспечивают невероятную скорость для игр и творчества. Они созданы на основе сверхэффективной архитектуры NVIDIA Ada Lovelace, которая обеспечивает качественный скачок как в производительности, так и в графических возможностях на базе ИИ. Погрузитесь в виртуальные миры с трассировкой лучей и сверхвысоким FPS с минимальной задержкой. Используйте возможности для творчества с беспрецедентным ускорением рабочего процесса.',
    price: 145999,
    rating: 5,
    stock: 4,
    brand: 'GIGABYTE',
    category: 'RTX 4090',
    images: ['../images/goodsImg/RTX4090/Gigabyte4090.webp', '../images/goodsImg/RTX4090/Gigabyte4090-2.webp'],
}, {
    id: 18,
    title: 'MSI GeForce RTX 4090 GAMING X TRIO',
    description: 'Играйте стильно! Серия GAMING получила обновленную систему охлаждения TRI FROZR 3 и способна поддерживать высокую производительность под любыми нагрузками. Все это предлагается в виде стильных устройств, способных удовлетворить жажду скорости любого геймера.',
    price: 151999,
    rating: 5,
    stock: 8,
    brand: 'MSI',
    category: 'RTX 4090',
    images: ['../images/goodsImg/RTX4090/MSI4090.webp', '../images/goodsImg/RTX4090/MSI4090-2.webp'],
}, {
    id: 19,
    title: 'GIGABYTE GeForce RTX 2060 Super WINDFORCE OC',
    description: 'Видеокарта GIGABYTE GeForce RTX 2060 Super WINDFORCE OC [GV-N206SWF2OC-8GD] – игровой видеоадаптер высокого класса, который способен удовлетворить потребности большинства любителей видеоигр. Модель оснащена широко известным графическим процессором GeForce RTX 2060 Super, произведенным с использованием техпроцесса 12 нм. Полную реализацию потенциальных возможностей видеопроцессора помогает обеспечить скоростная память GDDR6, объем которой составляет 8 ГБ.',
    price: 35499,
    rating: 4,
    stock: 12,
    brand: 'GIGABYTE',
    category: 'RTX 2060',
    images: ['../images/goodsImg/RTX2060/Gigabyte2060.webp', '../images/goodsImg/RTX2060/Gigabyte2060-2.webp'],
}, {
    id: 20,
    title: 'ASUS Dual GeForce RTX 2060 EVO',
    description: 'Видеокарта ASUS Dual GeForce RTX 2060 EVO с поддержкой технологии трассировки лучей обеспечит высокую производительность вашего компьютера в самых разных задачах — будь то игры на высоких настройках графики, монтаж видео или ретушь фото в профессиональных приложениях. В основе данной модели используется чип, выполненный с применением микроархитектуры Turing благодаря которому видеокарта имеет в 6 раз более высокую производительность по сравнению с моделями предыдущего поколения.',
    price: 30999,
    rating: 5,
    stock: 7,
    brand: 'ASUS',
    category: 'RTX 2060',
    images: ['../images/goodsImg/RTX2060/ASUS2060.webp', '../images/goodsImg/RTX2060/ASUS2060-2.webp'],
}];
